---
language: groovy
jdk:
- oraclejdk7
env:
  global:
  - TERM=dumb
  - GRADLE_OPTS="-Xmx768m -Xms256m -XX:MaxPermSize=256m -XX:+CMSClassUnloadingEnabled"
  - _JAVA_OPTIONS="-XX:-UseSplitVerifier"
  - secure: tvWIqrDyxdGkC43Us8BNwqU8aiu3NF5YWMPFW216n+KIO6HXJNyS6oV8gWCcUr/7MQzJEKmDvgnaRYykcX7tVfRQznWhXGro2V5Je6OOdvNrXu6Qr9/2Ue586NHWlA7rLhPOS9XOA6rFIKfPAbbjBwY2bhNXQ0ITxQ7oaT+EiyE=
before_script: "./gradlew populateDependencies testClasses"
script: "./travis-build.sh"
install: "/bin/true"
